version: "3.7"
services:
  frontend:
    image: venuzs/frontend:v1
    # build:
    #   context: /root/react-asp.net-mysql/frontend
    #   dockerfile: Dockerfile
    ports:
    - "3000:3000"


    environment:
      - BACKEND_IP=3.235.235.149
    depends_on:
    - dotnet

  dotnet:
    # build:
    #   context: /root/react-asp.net-mysql/backend/WebApplication1
    #   dockerfile: Dockerfile
    image: 
    container_name: dotnet
    ports:
    - "5000:80"
    depends_on:
    - mysql
#    networks:
#      - sdnet


  mysql:
    image: venuzs/mysql:v2
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
