image: mcr.microsoft.com/dotnet/core/sdk:3.1
pipelines:
  default:
    - step:
        script:
          - docker login -u venuzs -p venu@1234
          - docker build -t venuzs/backend:v1 .
          - docker push venuzs/backend:v1
options:
  docker: true
