apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-envoy
  labels:
    app: example-app-envoy
    system-type: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app-envoy
      system-type: envoy
  template:
    metadata:
      labels:
        app: example-app-envoy
        system-type: envoy
    spec:
      initContainers:
        - name: proxy-init
          image: "openpolicyagent/proxy_init:v5"
          args: ["-p", "8000", "-o", "8001", "-u", "1111"]
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            runAsNonRoot: false
            runAsUser: 0
      containers:
        - name: app
          image: "venuzs/backend:v3"
          ports:
            - containerPort: 80
          env:
          - name: POLICY_PATH
            value: /v1/data/application/main
        - name: envoy
          image: "envoyproxy/envoy:v1.21.2"
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: envoy-config-vol
          - readOnly: false
            mountPath: /run/opa/sockets
            name: opa-socket
          args:
          - "envoy"
          - "--config-path"
          - "/config/envoy.yaml"
          env:
          - name: ENVOY_UID
            value: "1111"
        - name: opa
          image: "openpolicyagent/opa:0.42.2-envoy-rootless"
          securityContext:
            runAsUser: 1111
          volumeMounts:
          - readOnly: true
            mountPath: /config
            name: opa-config-vol
          - readOnly: false
            mountPath: /run/opa/sockets
            name: opa-socket
          args:
          - "run"
          - "--server"
          - "--addr=http://127.0.0.1:8181"
          - "--config-file=/config/conf.yaml"
          - "--authorization=basic"
      env:
      volumes:
      - name: opa-config-vol
        configMap:
          name: opa-envoy-config
      - name: envoy-config-vol
        configMap:
          name: envoy-config
      - name: opa-socket
        emptyDir: {}